languge: java
jdk:
  - openjdk8

branches:
  only:
    - master


# travis ci 서버와 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * #brefore-deploy 이동후 전체 압축
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/com-jojoldu-book.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # travis repo setting에 설정된값
    secret_access_key: $AWS_SECRET_KEY # teavis repo setting에 설정된값

    bucket: rs-pro-build
    region: ap-northeast-1
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed : true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: rs-pro-build
    key: com-jojoldu-book.zip

    bundle_type: zip
    application: com-jojoldu-book
    deployment_group: com-jojoldu-book

    region: ap-northeast-1
    wait-until-deployed: true


# ci 실행 완료시 메일로 알람
#
notifications:
  email:
    recipients:
      - cheon2229@naver.com
